### ISSUE TITLE
feature request: bold author

### ISSUE THREAD

**Issue by SIBeckers** [martinec/grav-plugin-bibtexify#1]
I really enjoy the plugin, works beautifully.
I'm just writing to request the ability to bold all instances of an author but unfortunately do not program in php or js.

**Comment by martinec** [comment]
Thank you @SIBeckers for your suggestion. Starting v1.1.0 you can use a CSS rule to customize all instances of the author field. For example:

```
.bibtexify-author {
  font-weight: 700;
}
```

Here is the complete list of customizable styles:

- `bibtexify-address`
- `bibtexify-author`
- `bibtexify-booktitle`
- `bibtexify-chapter`
- `bibtexify-editor`
- `bibtexify-howpublished`
- `bibtexify-institution`
- `bibtexify-issn`
- `bibtexify-journal`
- `bibtexify-note`
- `bibtexify-number`
- `bibtexify-organization`
- `bibtexify-pages`
- `bibtexify-publisher`
- `bibtexify-school`
- `bibtexify-series`
- `bibtexify-title`
- `bibtexify-type`
- `bibtexify-volume`
- `bibtexify-year`

**Comment by SIBeckers** [comment]
Thanks! 
Another question or possible feature: Is it possible to bold all instances of just one author's name, e.g. to highlight one's own name in each bib entry?
For example:

John. Doe, James Tean, **Jane Dome** (2017) Some cool tite, _Cool Journal_
**Jane Dome**, Bill Tag, Git Hubbert (2016) Awesome title, _Journal of Awesome_

**Comment by martinec** [comment]
You can't do that using this plugin, but it would be possible using a bit of Javascript and CSS, something like:

Javascript:
```javascript
$(document).ready(function() {
  var author = "Jane Dome";
  var style  = "author-highlight";
  var re = new RegExp('(' + author + ')');
  $(".bibtexify-author:contains(" + author + ")").each(function() {
      var oldHtml = $(this).html();
      var newHtml = oldHtml.replace(re, "<span class='" + style + "'>$1</span>");
      $(this).html(newHtml);
  });
});
```

CSS:
```css
span.author-highlight {
  color: #1bbc9b;
  font-weight: 700;
}
```

For more information about the proposed solution, follow the next links:

- https://api.jquery.com/each/
- http://stackoverflow.com/a/4095842/2042871
- http://stackoverflow.com/a/12825110/2042871
- http://stackoverflow.com/a/494046/2042871

If you have any other further questions or feature requests related to the BibTeXify plugin, do not hesitate to open a new issue.
