### ISSUE TITLE
Can we have more citation types? 

### ISSUE THREAD

**Issue by danielforkner** [martinec/grav-plugin-bibtexify#6]
We use this plugin for our show references, but many of our citation types show up as "misc." For example, @'film' becomes misc. At the very least, we would like to differentiate between film/videos, academic journal articles, web articles, and books(working).  

Is there a list of all the acceptable categories?

**Comment by martinec** [comment]
Hi!  this is definitely possible but it needs additional [coding](https://github.com/martinec/grav-plugin-bibtexify/blob/master/js/bibtexify.js#L864). Can you share some examples of the references you are trying to show ?

**Comment by davidtorcivia** [comment]
I think you have all the standard BibTex formats added, but I'd love to see an @media or @av (audio visual) tag that could be used for film/tv/video/audio/etc.

**Comment by martinec** [comment]
Can you share a file or link including BibTex examples of `@media` and `@av` references ?

**Comment by av** [comment]
> I think you have all the standard BibTex formats added, but I'd love to see an @media or @av (audio visual) tag that could be used for film/tv/video/audio/etc.

👋🏻  here I am, not sure if could be of any use for film/tv/video/audio, sorry :)
