### ISSUE TITLE
Latest Grav Updates Seem to have broken Bibtexify

### ISSUE THREAD

**Issue by davidtorcivia** [martinec/grav-plugin-bibtexify#7]
Updated to grav 1.5.9 and then 1.5.10 (as well as associated backend plugins) and bibtexify seems to have broken. I imagine it's just a dependency that was updated and broke things but I haven't looked into it yet.

**Comment by martinec** [comment]
Does you get any error message or log ?

**Comment by davidtorcivia** [comment]
Okay finally have a chance to poke into it. Seems to be jQuery related.

Exception at bibtexify.js:2453 (`if(bInitHandedOff===false){_fnInitalise(oSettings)}})}})(jQuery);`) "ReferenceError:jQuery is not defined"

then next exception is:
"TypeError: bibtexify is not a function" referencing the script called into action by the `[/bibtexify]` shortcode. Specifically line `bibtexify("#bibtex-01e44102a2-", "bibtexify-01e44102a2-",`

and then there's a few related exceptions (as you'd expect)

**Comment by davidtorcivia** [comment]
Resolved this! Seems to have been a theme issue that cropped up. The bibtexify asset was being loaded before the jQuery asset causing those failures. Not sure why it suddenly became a problem without a theme update during the Grav core update to 1.5.9, but adding `{% do assets.addJs('jquery',101) %}` as the first section within the `{% block javascripts %}` block in the theme `head.html.twig` file resolved the problem. 

Thanks!
